name: Android CI

on:
  pull_request:
    branches: [ "dev", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Java (JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # Шаг 3: Скачивание, распаковка NDK и создание local.properties
      - name: Download and set up NDK r13b
        run: |
          # Скачиваем именно ту версию, что указана в README
          wget -q https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
          # Распаковываем в домашнюю директорию
          unzip -q android-ndk-r13b-linux-x86_64.zip -d $HOME
          # Создаем local.properties и прописываем путь к NDK
          echo "ndk.dir=$HOME/android-ndk-r13b" > local.properties
          echo "Created local.properties with NDK path"

      # Шаг 5: Сборка debug APK
      # Запускаем задачу 'assembleDebug', которая создает неподписанный APK.
      - name: Build with Gradle
        # run: gradle assembleLiteDebug
        # опции для ускорения
        run: gradle assembleLiteDebug --no-daemon --parallel


      # Шаг 6: Загрузка APK как артефакта
      # Находим собранный APK и загружаем его с помощью action 'upload-artifact'.
      # После этого его можно будет скачать со страницы workflow.
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          # Имя артефакта, который можно скачать со страницы workflow
          name: preview-eds-apk
          # Путь к файлу APK. Стандартный путь для debug-сборки.
          path: app/build/outputs/apk/lite/debug/*.apk

